hunter_config(ZLIB VERSION "1.3.0-p0" CMAKE_ARGS BUILD_SHARED_LIBS=On)
hunter_config(OpenSSL VERSION "3.5.0" CMAKE_ARGS ASM_SUPPORT=On BUILD_SHARED_LIBS=On)
hunter_config(hunter_venv VERSION "1.0.3" CMAKE_ARGS HUNTER_NOT_CI=On HUNTER_VENV_PYTHON_VERSION=3.7.0)
hunter_config(python VERSION 3.9.17 CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=On)
